# Generated by Django 4.2.3 on 2023-09-12 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения записи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения записи')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок title для страницы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('header', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='Текст')),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=32, verbose_name='Язык')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='posts.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
